### ISSUE TITLE
Base slug same as "Cars" page

### ISSUE THREAD

**Issue by defries** [barrykooij/wp-car-manager#164]
Instead of relying on a translation of this string in `PostType.php`: 
```
'slug'       => _x( 'vehicle', 'post type slug', 'wp-car-manager' ),
```
Wouldn't it make more sense for the page that is set is as the overview – Cars if you're running with the default set up in the installation wizard – to use that page as a default for the slug? To me that makes more sense than using a translation for it. Especially in the case where you don't need to use a translation, for instance when you're using the default `en_US` but you do want to have control over your base slug. 

Best I can tell, using a `gettext` filter doesn't yield any results, so IMO, using a page as root actually provides for a much better user experience.

**Comment by barrykooij** [comment]
We're not setting the slug to look like the cars are children of the overview page because there can be multiple overview pages. The way the slug of the post type currently works is chosen because other large plugins like WooCommerce use the same technique and users seem to be happy with it.

The slug can be changed via a filter, like this: https://gist.github.com/barrykooij/12fc9184f96dadb08f60
