### ISSUE TITLE
Make vehicle wrapper <article> instead of <div>

### ISSUE THREAD

**Issue by barrykooij** [barrykooij/wp-car-manager#29]
https://github.com/barrykooij/wp-car-manager/blob/master/templates/content-single-vehicle.php#L14

**Comment by defries** [comment]
Just to further explain. Most of the time you'll want to have a `article` here instead of an opening `div`, but if you were to take this any further as to make that entire line either filterable and _unhookable_ that'd be great. This will help in integrating this plugin with Genesis much better. See the difference in output with WPCM in Genesis: ![](http://i.remk.us//1p/ipfwm71vogooc.png)  and the expected behaviour: ![](http://i.remk.us//3l/sz48igjo84cw0.png)

**Comment by defries** [comment]
Additionally on L55 adding the class `entry-content` would also make existing styling in case of Genesis match better. Resulting in `<div class="wpcm-vehicle-conten entry-content">`
